# GET RICH OR DIE TRYIN!


Scrap data from https://www.alphavantage.co/


Welcome to Alpha Vantage! Your API key is: ZSGQT6U88P0M37ZD. Please record this API key at a safe place for future data access.

In [1]:
import requests

r = requests.get('https://www.alphavantage.co/query?function=OVERVIEW&symbol=TSLA&apikey=ZSGQT6U88P0M37ZD')

In [2]:
from bs4 import BeautifulSoup

html = r.content
html

soup = BeautifulSoup(html, 'html.parser')

In [3]:
soup

{
    "Symbol": "TSLA",
    "AssetType": "Common Stock",
    "Name": "Tesla, Inc",
    "Description": "Tesla, Inc. is an American electric vehicle and clean energy company based in Palo Alto, California. Tesla's current products include electric cars, battery energy storage from home to grid-scale, solar panels and solar roof tiles, as well as other related products and services. In 2020, Tesla had the highest sales in the plug-in and battery electric passenger car segments, capturing 16% of the plug-in market (which includes plug-in hybrids) and 23% of the battery-electric (purely electric) market. Through its subsidiary Tesla Energy, the company develops and is a major installer of solar photovoltaic energy generation systems in the United States. Tesla Energy is also one of the largest global suppliers of battery energy storage systems, with 3 GWh of battery storage supplied in 2020.",
    "CIK": "1318605",
    "Exchange": "NASDAQ",
    "Currency": "USD",
    "Country": "USA",
    "Sector": "MANUFACTURING",
    "Industry": "MOTOR VEHICLES &amp; PASSENGER CAR BODIES",
    "Address": "3500 DEER CREEK RD, PALO ALTO, CA, US",
    "FiscalYearEnd": "December",
    "LatestQuarter": "2021-03-31",
    "MarketCapitalization": "654891024384",
    "EBITDA": "4551000064",
    "PERatio": "681.1824",
    "PEGRatio": "3.7112",
    "BookValue": "23.901",
    "DividendPerShare": "None",
    "DividendYield": "0",
    "EPS": "0.998",
    "RevenuePerShareTTM": "38.052",
    "ProfitMargin": "0.0318",
    "OperatingMarginTTM": "0.0601",
    "ReturnOnAssetsTTM": "0.0299",
    "ReturnOnEquityTTM": "0.0716",
    "RevenueTTM": "35939999744",
    "GrossProfitTTM": "6630000000",
    "DilutedEPSTTM": "0.998",
    "QuarterlyEarningsGrowthYOY": "21.304",
    "QuarterlyRevenueGrowthYOY": "0.736",
    "AnalystTargetPrice": "652.52",
    "TrailingPE": "681.1824",
    "ForwardPE": "140.8451",
    "PriceToSalesRatioTTM": "19.3977",
    "PriceToBookRatio": "26.1041",
    "EVToRevenue": "16.589",
    "EVToEBITDA": "127.2591",
    "Beta": "1.9951",
    "52WeekHigh": "895.9",
    "52WeekLow": "189.704",
    "50DayMovingAverage": "608.7347",
    "200DayMovingAverage": "695.4799",
    "SharesOutstanding": "963329984",
    "SharesFloat": "775057145",
    "SharesShort": "40046181",
    "SharesShortPriorMonth": "39869947",
    "ShortRatio": "1.28",
    "ShortPercentOutstanding": "0.04",
    "ShortPercentFloat": "0.0517",
    "PercentInsiders": "19.63",
    "PercentInstitutions": "42.664",
    "ForwardAnnualDividendRate": "0",
    "ForwardAnnualDividendYield": "0",
    "PayoutRatio": "0",
    "DividendDate": "None",
    "ExDividendDate": "None",
    "LastSplitFactor": "5:1",
    "LastSplitDate": "2020-08-31"
}

In [4]:
import time
import pandas as pd
import json


API_URL = "https://www.alphavantage.co/query"
comp_overview=[]
symbols= ["TSLA", "MSFT", "AAPL"]

#symbols=['NVDA','POOL','CRM','WST','VRTX','ADBE','CDNS','IRBT','FIX','LRCX','INTU','BBY','BLK','EXPD','DECK','MSFT','AMAT','IDXX','TDOC','RCM','HBI','HD','PWR','BCC','A','TROW','FAST','BWXT','MTD','PLD','FDS','EW','PG','RMD','ZBRA','KMB','CMI','GWW','TRMB','MLHR','CLX','BEAT','EQIX','TVTY','KSU','TXN','PETQ','DGX','CHRW','PDCO']



for symbol in symbols:
    data = {
        "function": "OVERVIEW",
        "symbol": symbol,
        "apikey": "ZSGQT6U88P0M37ZD",
        }

    response = requests.get(API_URL, params=data)
    time.sleep(15)
    comp_overview.append(response.json())

### GET THE OVERVIEW DATA OF A NUMBER OF CERTAIN LISTED COMPANIES IN STOCK EXCHANGE

In [5]:
comp_overview=pd.json_normalize(comp_overview)

In [6]:


import pandas as pd 
#fileName = 'comp_overview'
#comp_overview.to_csv(fileName)

In [7]:
API_URL = "https://www.alphavantage.co/query"
income_statement=[]
#symbols= ["TSLA", "MSFT", "IBM"]

symbols=['NVDA','POOL','CRM','WST','VRTX','ADBE','CDNS','IRBT','FIX','LRCX','INTU','BBY','BLK','EXPD','DECK','MSFT','AMAT','IDXX','TDOC','RCM','HBI','HD','PWR','BCC','A','TROW','FAST','BWXT','MTD','PLD','FDS','EW','PG','RMD','ZBRA','KMB','CMI','GWW','TRMB','MLHR','CLX','EQIX','TVTY','KSU','TXN','PETQ','DGX','CHRW','PDCO']


for symbol in symbols:
    data = {
        "function": "INCOME_STATEMENT",
        "symbol": symbol,
        "apikey": "ZSGQT6U88P0M37ZD",
        }

    response = requests.get(API_URL, params=data)
    time.sleep(15)
    income_statement.append(response.json())

### GET THE INCOME STATEMENT DATA OF A NUMBER OF CERTAIN LISTED COMPANIES IN STOCK EXCHANGE

In [8]:
#df_income_statement=pd.json_normalize(income_statement[1]['annualReports'])


df_income_final=pd.DataFrame()


for i in income_statement:
    df_income_statement=pd.json_normalize(i['annualReports'])
    df_income_statement['symbol']=i['symbol']
    df_income_final=pd.concat([df_income_final,df_income_statement])

In [9]:
df_income_final

,fiscalDateEnding,reportedCurrency,grossProfit,totalRevenue,costOfRevenue,costofGoodsAndServicesSold,operatingIncome,sellingGeneralAndAdministrative,researchAndDevelopment,operatingExpenses,...,depreciationAndAmortization,incomeBeforeTax,incomeTaxExpense,interestAndDebtExpense,netIncomeFromContinuingOperations,comprehensiveIncomeNetOfTax,ebit,ebitda,netIncome,symbol
0,2021-01-31,USD,10396000000,16491000000,9317000000,6279000000,4532000000,1940000000,3924000000,5864000000,...,1098000000,4409000000,77000000,184000000,4332000000,4350000000,4593000000,5691000000,4332000000,NVDA
1,2020-01-26,USD,6768000000,10866000000,5624000000,4150000000,2846000000,1093000000,2829000000,3922000000,...,381000000,2970000000,174000000,52000000,2796000000,2809000000,3022000000,3403000000,2796000000,NVDA
2,2019-01-27,USD,7171000000,11658000000,5798000000,4545000000,3804000000,991000000,2376000000,3367000000,...,262000000,3896000000,-245000000,58000000,4141000000,4147000000,3954000000,4216000000,4141000000,NVDA
3,2018-01-28,USD,5822000000,9714000000,3892000000,3892000000,3210000000,815000000,1797000000,2612000000,...,199000000,3196000000,149000000,80000000,3047000000,3045000000,3257000000,3456000000,3047000000,NVDA
4,2017-01-29,USD,4063000000,6910000000,2847000000,2847000000,1934000000,663000000,1463000000,2129000000,...,187000000,1905000000,239000000,79000000,1666000000,1654000000,1963000000,2150000000,1666000000,NVDA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,2021-04-24,USD,1203130000,5912066000,4708936000,5701459000,210607000,21357000,None,1016439000,...,None,200803000,44822000,32418000,155109000,189556000,225087000,303111000,155981000,PDCO
1,2020-04-25,USD,1197410000,5490011000,4292601000,4292601000,-572119000,28728000,None,1125210000,...,82182000,-589486000,-1040000,49921000,-589367000,-595430000,-547699000,-489937000,-588446000,PDCO
2,2019-04-27,USD,1190775000,5574523000,4383748000,4383748000,137716000,42826000,None,1053059000,...,82773000,106980000,23352000,39666000,82876000,69581000,146646000,220489000,83628000,PDCO
3,2018-04-28,USD,1199366000,5465683000,4266317000,4266317000,219889000,49751000,None,979477000,...,83816000,179263000,-21711000,46743000,200974000,218669000,226006000,303705000,200974000,PDCO
4,2017-04-29,USD,1301397000,5593127000,4291730000,4291730000,287928000,52340000,None,1013469000,...,83818000,247986000,77093000,43060000,173788000,146188000,291046000,371746000,170893000,PDCO

In [10]:
fileName = 'income_statement'
df_income_final.to_csv(fileName)

In [11]:

#income_symbol=pd.DataFrame()
#income_symbol_final=[]

#for i in income_statement:
#    income_symbol['symbol']=i['symbol']
#    income_symbol_final.append(i['symbol'])

In [12]:

#income_statement_step2=[]
#income_statement_symbol=[]


#for data in income_statement:
#        income_statement_step2.append(data['annualReports'][0])


#for data in income_statement:    
#       income_statement_symbol.append(data['symbol'])

In [13]:
import alpha_vantage
import datetime as dt

In [14]:
from alpha_vantage.timeseries import TimeSeries
app = TimeSeries('ZSGQT6U88P0M37ZD',output_format='pandas')
#help(app)

MSFT = app.get_daily_adjusted('MSFT', outputsize='full')
MSFT

(            1. open  2. high  3. low  4. close  5. adjusted close   6. volume  \
 date
 2021-06-24   266.16   267.85  265.47   266.690         266.690000  21446867.0
 2021-06-23   265.99   266.83  264.43   265.275         265.275000  19518681.0
 2021-06-22   262.72   265.79  262.40   265.510         265.510000  24694090.0
 2021-06-21   259.82   263.52  257.92   262.630         262.630000  26696119.0
 2021-06-18   259.63   262.30  258.75   259.430         259.430000  37202217.0
 ...             ...      ...     ...       ...                ...         ...
 1999-11-05    91.81    92.87   90.50    91.560          29.073675  35083700.0
 1999-11-04    92.31    92.75   90.31    91.750          29.134007  27119700.0
 1999-11-03    92.94    93.50   91.50    92.000          29.213392  22258500.0
 1999-11-02    92.75    94.50   91.94    92.560          29.391212  23174500.0
 1999-11-01    93.25    94.19   92.12    92.370          29.330880  26630600.0

             7. dividend amount  8. split coefficient
 date
 2021-06-24                 0.0                   1.0
 2021-06-23                 0.0                   1.0
 2021-06-22                 0.0                   1.0
 2021-06-21                 0.0                   1.0
 2021-06-18                 0.0                   1.0
 ...                        ...                   ...
 1999-11-05                 0.0                   1.0
 1999-11-04                 0.0                   1.0
 1999-11-03                 0.0                   1.0
 1999-11-02                 0.0                   1.0
 1999-11-01                 0.0                   1.0

 [5447 rows x 8 columns],
 {'1. Information': 'Daily Time Series with Splits and Dividend Events',
  '2. Symbol': 'MSFT',
  '3. Last Refreshed': '2021-06-24',
  '4. Output Size': 'Full size',
  '5. Time Zone': 'US/Eastern'})

In [15]:
#from alpha_vantage.foreignexchange import ForeignExchange

#app = ForeignExchange('ZSGQT6U88P0M37ZD',output_format='pandas')

#eurusd = app.get_currency_exchange_intraday('EUR', 'USD')
#print(eurusd[0])

In [16]:
#df_income_statement.to_csv('test.csv')